export const GET_GLOBAL_CORONA_STATS = "GET_GLOBAL_CORONA_STATS";
export const GET_COUNTRY_STATISTICS = "GET_COUNTRY_STATISTICS";
export const GET_COUNTRY_DAILY_STATISTICS = "GET_COUNTRY_DAILY_STATISTICS";

